name: ci

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Git Commit Info
        run: |
          GIT_COMMIT=$(git rev-parse --short HEAD)
          echo "GIT_COMMIT=${GIT_COMMIT}" >> $GITHUB_ENV
      - name: Setup Docker Image Version Number
        run: |
          TAG=${{ github.ref_name }}
          echo "DOCKER_IMAGE_VERSION=${TAG#v}" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            GIT_COMMIT=${{env.GIT_COMMIT}}
            PROJECT_ID:${{secrets.PROJECT_ID}}
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest,${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{env.DOCKER_IMAGE_VERSION}}